### PR TITLE
Fix event card wrong avatar issue

### LINKED ISSUE #3069: [BUG] When filtering events the profile picture is not correct
### Description

When filtering events the profile picture is not correct

### Screenshots

Without filtering (all events)
image
-> profile picture of eddie

when filtering for cfp open

image
wrong user image
but it is linking to the right linkfree profile (eddies)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Btwonu**
Closes #3069 

## Changes proposed
Wrong avatars being loaded was caused by React not properly following the `key` properties on `EventCard` components.
I've added a workaround, by adding an `id` property to the event objects after they're being fetched. 
I imagine later down the road, the event object structure will be changed and they will come with ids from the database, so those can be used as a `key`.

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

2023-01-11 12_31_27-Window
2023-01-11 12_31_38-Events the community members are going to

## Note to reviewers
This is more or less my first pull request, I apologize if I'm doing something wrong.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3150"></a>

### CODE REVIEW

File: pages/events.js [hunk 1]
```diff
@@ -49,10 +51,10 @@ export default function Events({ events }) {
         {!events.length && <Alert type="info" message="No events found" />}
         <ul role="list" className="divide-y divide-gray-200">
           {categorisedEvents[eventType].map((event, index) => (
-            <EventCard event={event} username={event.username} key={index} />
+            <EventCard event={event} username={event.username} key={event.id} />
```
Comment (eddiejaoude) [inline pages/events.js:54]: Thank you for the fix 👍 

Could we concatenate the event name with the username?

Comment (Btwonu) [reply pages/events.js]: Sure, thanks for the feedback!

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  thank you for fixing 💯
