### PR TITLE
fix: NavLink active state not persist

### LINKED ISSUE #5190: [BUG] - NavLink active state not persist
### Description

 When we go from the `/docs` page to the `/docs/quickstart` page, the navigation link for the current page does not have an active state. The active state is only visible when we are on the `/docs` page. This behavior is confusing and can be improved.
 
 Here is the video of the current behavior:
 
 
https://user-images.githubusercontent.com/94737463/222326097-eea2b3f2-5576-4ef2-ab89-acf8e8e5d091.mp4

---

Here is the video of the expected behavior:

- For desktop screen:

https://user-images.githubusercontent.com/94737463/222326307-e8cb0aa5-4d42-46e1-819d-147a73c53bc4.mp4

- For mobile screen:

https://user-images.githubusercontent.com/94737463/222326364-0464f1d6-8550-450c-98a8-9551eddfe317.mp4

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JunDevHarsh**
## Fixes Issue

fixes #5190 

## Changes proposed

The proposed change replaces a direct string comparison between the `path` and `item` variables with a more flexible check that extracts a specific substring from the path and compares it to a modified version of the `url` property of the item object. This change allows for more robust matching of URLs with different structures, while still achieving the same functional outcome.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Video Preview

Here is the video of the resulted behavior:

- For desktop screen:

https://user-images.githubusercontent.com/94737463/222326307-e8cb0aa5-4d42-46e1-819d-147a73c53bc4.mp4

- For mobile screen:

https://user-images.githubusercontent.com/94737463/222326364-0464f1d6-8550-450c-98a8-9551eddfe317.mp4

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5197"></a>

### CODE REVIEW

**Review by iamthecloverly — DISMISSED** [review]

File: components/navbar/NavLink.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default function NavLink({ path, item, mode, setIsOpen, onClick }) {
       "text-gray-300 hover:ring-2 hover:ring-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium";
   }
 
-  if (path === item.url) {
+  if (path?.split("/")[1] === item.url.replace("/", "")) {
```
Comment (eddiejaoude) [inline components/navbar/NavLink.js:12]: I think it would be better to do a similar match on each side using the split and the 2nd item (`[1]`)?

Comment (JunDevHarsh) [reply components/navbar/NavLink.js:12]: I think you are right, at some point we need to check the other side also. But currently, we are just focusing on making an active state to the navbar menu list.

Comment (eddiejaoude) [reply components/navbar/NavLink.js:12]: I think this is a straight forward improvement now, which would reduce having a bug in the future

Comment (JunDevHarsh) [reply components/navbar/NavLink.js]: > I think this is a straight forward improvement now, which would reduce having a bug in the future

I have updated the code based on matching each side.

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍 

Sorry for the slow review
