### PR TITLE
fix: Markdown not being rendered in the description when sharing profile

### LINKED ISSUE #3950: Fix social media preview of LinkFree profile
### Description

I shared my linkfree profile URL with a friend and I spotted - in profile preview the bio tag appears as markdown.
It would be good if it appears as simple text without the markdown symbols.

### Screenshots

WhatsApp Image 2023-01-25 at 13 40 53
Have a look below my name - asterisk symbols also appear.

### Additional information

I don't know is it a bug or whatever! I thought it could be improved - so I learned how to refer an issue in an open source project!

### PR DESCRIPTION
**Pull request by ChinmayMhatre**
## Fixes Issue
closes #3950 

## Changes proposed

Remove markdown from the description for now. as discussed in the issue. maybe markdown could be added if any new solution is found.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4898"></a>

### CODE REVIEW

**Review by sansarmaske — DISMISSED** [review]
Works as expected.

File: pages/[username].js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default function User({ data, BASE_URL }) {
     <>
       <PageHead
         title={data.name}
-        description={data.bio}
+        description={data.bio.replaceAll("*","")}
```
Comment (eddiejaoude) [inline pages/[username].js:91]: we will also need to remove other types of markdown that people might use

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Looks good, but left an inline comment

File: pages/[username].js (hunk 1 above)
Comment (ChinmayMhatre) [reply pages/[username].js:91]: Oh yeah! I missed that. I'll try to create a function before passing in to `description`

Comment (eddiejaoude) [reply pages/[username].js:91]: It might be easier to do a regex that extracts the text and punctuation

**Comment by ChinmayMhatre** [comment]
Would using something like this plugin be okay?

https://www.npmjs.com/package/strip-markdown

File: pages/[username].js (hunk 1 above)
Comment (ChinmayMhatre) [reply pages/[username].js:91]: Oh, like just letters, spaces and commas?

Comment (ChinmayMhatre) [reply pages/[username].js:91]: I looked around for this. We can certainly do this with regex. It may not take into account all the complex cases. I used chatgpt to create it for as many cases as we can. We can try this for now and add an external library if this fails

**Comment by ChinmayMhatre** [comment]
Could we use something like this : https://www.npmjs.com/package/strip-markdown

I think regex wouldn't take into account complex cases. What do you think?

**Comment by eddiejaoude** [comment]
yeah that could work 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good, thank you 👍

**Comment by eddiejaoude** [comment]
I think there is a promise issue...

Screenshot 2023-02-23 at 08 19 48

**Comment by eddiejaoude** [comment]
I have fixed in this PR https://github.com/EddieHubCommunity/LinkFree/pull/5022
