### PR TITLE
Fix: spacing between add repo form and repo list.

### LINKED ISSUE #8606: [BUG] Space between Add Repo button and list of repo
### Description

- Some space should be added between **Add Repo** button & All the added repositories of the user.

### Screenshots

Screenshot 2023-08-10 224102

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Rosh008**
## Fixes Issue

Closes #8606

## Changes proposed
Add margin to form component

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot 2023-08-18 at 6 34 04 PM

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8694"></a>

### CODE REVIEW

File: pages/account/manage/repos.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ export default function ManageRepos({ BASE_URL, repos }) {
           additionalMessage={showNotification.additionalMessage}
         />
 
-        <form onSubmit={handleSubmit}>
+        <form className="mb-4" onSubmit={handleSubmit}>
```
Comment (sital002) [inline pages/account/manage/repos.js:139]: I think mb-4 will be too much of space mb-2 might be ideal for this and instead of adding styles on form element  why don't you  add styles in the button element.

Comment (Rosh008) [reply pages/account/manage/repos.js:139]: Directly applying margin style to the button is breaking the button UI.

**Comment by sital002** [comment]
@Rosh008 Can you provide some more dwtail on applying styles on button is breakung the ui maybe provide some images related to the issue.

**Comment by Rosh008** [comment]
@sital002 
Screenshot 2023-08-18 at 8 18 11 PM

**Review by sital002 — COMMENTED** [review]
Wrap the button element in a div and then add necessary styles to the div element.

**Comment by Rosh008** [comment]
> Wrap the button element in a div and then add necessary styles to the div element.

Yaa sure but why not have them on the form itself instead of wrapping the button with an extra div for the sole purpose of adding a single style value ?

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
