### PR TITLE
fix: profile card hover color

### LINKED ISSUE #8176: [BUG] Profile Card Hover in Dark Mode should have orange border
### Description

**Description:**
When the user is in dark mode and hovers over the profile card, the expected behaviour is for the card to display an orange border similar to search bar

**Steps to Reproduce:**
1. Enable dark mode in the application.
2. Navigate to a page where the profile card is displayed.
3. Hover over the profile card.

https://github.com/EddieHubCommunity/LinkFree/assets/96465597/402266c2-b87b-480b-aa87-2ccf20847454

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adarshmalviya12**
## Fixes Issue 

Closes #8176

## Changes proposed

Fixed the issue where the profile card did not display an orange border when hovered in dark mode.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://github.com/EddieHubCommunity/LinkFree/assets/96465597/56d02566-7191-4531-a286-b1af6d0ab772

This is my first contribution to this project, and I'm excited to be a part of the community. I kindly request your feedback on my changes. If there are any areas for improvement or suggestions, I'm eager to learn and make the necessary updates. Thank you for your time and guidance!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8192"></a>

### CODE REVIEW

**Review by akkshitgupta — APPROVED** [review]

File: components/user/UserCard.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ export default function UserCard({ profile }) {
         />
       </div>
       <div>
-        <h3 className="text-xl justify-center text-center mb-2 text-tertiary-medium font-bold">
+        <h3 className="text-xl justify-center text-center mb-2 text-tertiary-medium font-bold ">
```
Comment (eddiejaoude) [inline components/user/UserCard.js:23]: I don't think the extra space is required here?

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍  thank you!
