### PR TITLE
fix: Failing to add repo with trailing slash

### LINKED ISSUE #8560: [BUG] Failed to add Github Repo
### Description

After successful logging in to my account, when I try to add GitHub repo in the repos section, LinkFree fails to add it.
I want to add an Open-Source project of mine. It's called [Drifty](https://github.com/SaptarshiSarkar12/Drifty/).
See the below screenshot to learn more about the error.

edit: remove trailing slash from url 
- from https://github.com/SaptarshiSarkar12/Drifty/
- to https://github.com/SaptarshiSarkar12/Drifty

### Screenshots

Screenshot from 2023-08-07 23-32-30

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Fixes Issue
Fixes #8560

## Changes proposed
I have made the following changes :
- I added a condition in the **_repo.js_** file in the **api/account/manage** directory, to check **if the url entered by the user contains a trailing slash**. If it contains, then the **_url will be changed to the one without the trailing slash_** before the GitHub API call is made, without _changing the url in the text box placeholder_. So, the _user does not get to know about the issue with the trailing slash_.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
See the below video recording of the fix implemented via this PR.

[Screencast from 2023-08-13 19-50-44.webm](https://github.com/EddieHubCommunity/LinkFree/assets/105960032/825aba3c-a005-4ad1-90d0-cbfb23425a22)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8636"></a>

### CODE REVIEW

File: pages/account/manage/repos.js [hunk 1]
```diff
@@ -51,10 +51,13 @@ export default function ManageRepos({ BASE_URL, repos }) {
...
   const [repoList, setRepoList] = useState(repos || []);
-  const [url, setUrl] = useState("");
+  let [url, setUrl] = useState("");
 
   const handleSubmit = async (e) => {
     e.preventDefault();
+    if (url.endsWith("/")) {
+        url = url.substring(0, url.length - 1);
+    }
     const res = await fetch(`${BASE_URL}/api/account/manage/repo`, {
```
Comment (tamalCodes) [inline pages/account/manage/repos.js:61]: It's generally not recommended to directly modify state variables. The useState hook provides a setter function (in your case, setUrl) to update the state safely. Maybe we can do something like this ? 

```js
setUrl(url.slice(0, -1));
```

The `setUrl(url.slice(0, -1));` and `url.substring(0, url.length - 1);` is essentially the same, removing the last character.

Comment (SaptarshiSarkar12) [reply pages/account/manage/repos.js:61]: Yeah @tamalCodes, I know about it. But, the `setUrl()` method sets the formatted URL in the text box. So, **the user needs to click on the `Add Repo` button again** which I don't think is a good idea. (**_Please check the below video_**)
Let me know if you have any other options.

[Screencast from 2023-08-13 23-28-20.webm](https://github.com/EddieHubCommunity/LinkFree/assets/105960032/595465f0-8bba-4c9f-abdb-bdf9ddae18f9)

Comment (badrivlog) [reply pages/account/manage/repos.js:61]: I think we could do something like this-
```js
const repoUrl = url.endsWith("/") ? url.slice(0, -1) : url;
```

**Comment by Shivamdwivedi1403** [comment]
done

File: pages/account/manage/repos.js (hunk 1 above)
Comment (SaptarshiSarkar12) [reply pages/account/manage/repos.js:61]: @badrivlog Yes, this can be done. Thank you for the suggestion.
I am going to push this changes as mentioned by @badrivlog.

Comment (SaptarshiSarkar12) [reply pages/account/manage/repos.js:61]: @badrivlog I am facing a runtime error when I try to make your suggested changes as under. Please suggest a fix for this.
```
    const repoUrl = url.endsWith("/") ? url.slice(0, -1) : url;
    const res = await fetch(`${BASE_URL}/api/account/manage/repo`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ repoUrl }),
    });
```
The screenshot of the error is - 
Screenshot from 2023-08-14 09-38-51

**Comment by badrivlog** [comment]
Looks Good 👍

**Comment by SaptarshiSarkar12** [comment]
> Looks Good :+1:

Thank you for reviewing @badrivlog :smile: !

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by SaptarshiSarkar12** [comment]
Thank you @eddiejaoude for the merge :smile: :tada: !
