### PR TITLE
fix: date format helper

### LINKED ISSUE #7650: Add date formatting functionality
### Description

To avoid repetition, either add a date formatting helper function or add a date library such as date fns.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
## Fixes Issue

fixes #7650 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8380"></a>

### CODE REVIEW

File: services/utils/dateFormat.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+      break;
+    case "long":
+      dateTimeStyle = {
+        dateStyle: "full",
+        timeStyle: "long",
+      };
+      break;
+  }
+
+  return new Intl.DateTimeFormat("en-GB", dateTimeStyle).format(new Date(date));
```
Comment (dan-mba) [inline services/utils/dateFormat.js:16]: This will confuse people as dates will be displayed as `DD/MM/YYYY` everywhere.

Comment (eddiejaoude) [reply services/utils/dateFormat.js:16]: But isn't that what we have at the moment? I just abstracted the duplicate code

Comment (dan-mba) [reply services/utils/dateFormat.js:16]: I might be, but it shouldn't.

On the server side, there should be a consistent format.
But on the client side, it should use the local format.
For example in components/event/EventCard.js, the code in the `useEffect` should use local format.

With the function this way, there is no option to use local time.
To specify to use local time, the function should look like:
```js
Intl.DateTimeFormat(undefined, options)
```

Comment (eddiejaoude) [reply services/utils/dateFormat.js:16]: Yep makes sense 👍  I will update

File: pages/account/statistics.js [hunk 2]
```diff
@@ -95,15 +96,10 @@ export async function getServerSideProps(context) {
...
-  const dateTimeStyle = {
-    dateStyle: "short",
-  };
   const dailyViews = data.profile.daily.slice(-30).map((day) => {
     return {
       views: day.views,
-      date: new Intl.DateTimeFormat("en-GB", dateTimeStyle).format(
-        new Date(day.date)
-      ),
+      date: dateFormat({ format: "short", date: day.date }),
```
Comment (dan-mba) [inline pages/account/statistics.js:102]: This code will have hydration issues.

When SSR is run, the locale will be "en-GB" (using Vercel in London).
On the client, it will be local (ex "en-US"), which if different, will force a complete re-render.

The way to avoid this, is to do an initial conversion in getServerSideProps. Store the value in a state variable. Then update on render with a useEffect.

Comment (eddiejaoude) [reply pages/account/statistics.js:102]: Oh wow ok, I didn't realise that, so that problem exists already?

Comment (dan-mba) [reply pages/account/statistics.js:102]: No.

It is caused by the switch from "en-GB" to local.

Comment (eddiejaoude) [reply pages/account/statistics.js:102]: Oh I see! Thank you!

I tried to do the dynamic way with useEffect, but had some weird issues. I will put it back to `en-GB` and further improvements can come later

Comment (eddiejaoude) [reply pages/account/statistics.js]: Pushed, hopefully this is ok now?

Comment (dan-mba) [reply pages/account/statistics.js]: Looks good for this PR. I will look into making some improvements in a future PR.

Comment (eddiejaoude) [reply pages/account/statistics.js]: Great! Thank you Dan ❤️
