### PR TITLE
Fix dark mode display issue for bio label

### LINKED ISSUE #8664: [BUG] Bio label is not shown in dark mode
## Problem
- Inside **Profile Edit** section, Bio label is not visible for dark mode.

## Expected solution
- Label color of **Bio** should be White.
- Background color of text area should be dark.

### Screenshots

- Dark Mode
image

<br>

- Light Mode
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KSSaiTeja**
## Fixes #8664 

fixes #8664 

closes #8664 

## Changes proposed

i fixed a bug that, the in `account/manage/profile` page, the **BIO** label is not visible in dark mode, i changed the color of this label to white and fixed the issue. So that, it resolves issue where the bio label was not visible in dark mode.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

no screenshots taken, but check the issue, it won't repeat again

## Note to reviewers

This pull request addresses the issue where the bio label was not being displayed correctly in dark mode. I've fixed the styling so that the bio label now shows up properly even in dark mode.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8669"></a>

### CODE REVIEW

**Comment by KSSaiTeja** [comment]
i have receive a mail to work on it, but as i am new to open source, before that mail i raised a PR, please take this #8669 as the fix for #8664 and merge it..
Thank you

**Comment by KSSaiTeja** [comment]
i have made a **new commit** in this, the font color updated as it defined in config file. Please make merge to main branch. As this is my first opensource contribution, it would be more inspirational to work on more opensource contributions.

Thank You.

File: components/form/Textarea.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export default function Textarea({ name, value, label, ...restProps }) {
           rows={4}
           name={name}
           id={name}
-          className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
+          className="block w-full rounded-md border-0 py-1.5 text-gray-900  shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
```
Comment (eddiejaoude) [inline components/form/Textarea.js:15]: This change is not required 

```suggestion
          className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
```

File: components/form/Textarea.js [hunk 2]
```diff
@@ -3,7 +3,7 @@ export default function Textarea({ name, value, label, ...restProps }) {
     <div>
       <label
         htmlFor={name}
-        className="block text-sm font-medium leading-6 text-gray-900"
+        className="block text-sm font-medium leading-6 text-gray-900 dark:text-primary-low"
```
Comment (eddiejaoude) [inline components/form/Textarea.js:6]: Thank you for the dark mode fix, we should also fix light mode

```suggestion
        className="block text-sm font-medium leading-6 text-primary-high dark:text-primary-low"
```

**Review by eddiejaoude — APPROVED** [review]
Thank you for the contribution 👍

**Comment by KSSaiTeja** [comment]
> Thank you for the contribution 👍

My pleasure to contiribute.. Let me know if any issues are there?
