### PR TITLE
Fix: Icon names work Capitalised and lowercase

### LINKED ISSUE #805: [DOCS] Available icons names are misleading
### Description

I found many users has their icon's key value first letter in uppercase, which causing a problem of not showing icons in milestone 

### Screenshots

firefox_Twn30Smhuc
before fixing the issue

firefox_b2glkj4bC8
after fixed

### Additional information

it can be solved either by converting icon value into lowercase on runtime or just by correcting the available icons name on ReadME

### PR DESCRIPTION
**Pull request by nathgoutam93**
## Fixes Issue

closes #805

## Check List 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/811"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Review by shreyaansjain06 — APPROVED** [review]

**Review by krishguptadev — APPROVED** [review]

**Review by ssensalo — APPROVED** [review]

File: src/Components/Links.js [hunk 1]
```diff
@@ -20,37 +20,47 @@ function Links({ links }) {
...
-            >
-              <i className={`pi pi-${link.icon} p-px-2`}></i>
-              <span className="p-px-3">{link.name}</span>
-            </Button>
-          ))}
+          .filter((link) =>
+            Object.keys(colors).includes(link.icon?.toLowerCase()),
+          )
+          .map((link, index) => {
+            const icon = link.icon.toLowerCase()
```
Comment (eddiejaoude) [inline src/Components/Links.js:27]: The `toLowerCase()` could probably be done once in a map before the filter

Comment (eddiejaoude) [reply src/Components/Links.js:27]: Or even better, when the data is loaded at the source so it is not required in multiple places

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Duplicate code, see inline comments

File: src/Components/Home/Users.js [hunk 2]
```diff
@@ -32,8 +32,8 @@ function Users({ list }) {
         }
       />
       <div className="user-list p-d-flex p-flex-wrap p-jc-center">
-        {!!filteredList &&
-          filteredList.length > 0 &&
+        {
+          filteredList?.length > 0 &&
```
Comment (eddiejaoude) [inline src/Components/Home/Users.js:36]: This is not related to this PR, it should go in another PR. But I am not sure it is needed, from the React docs they recommend keeping it the previous style https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

File: src/Components/UserProfile/ProfilePage.js [hunk 3]
```diff
@@ -1,20 +1,38 @@
...
+  const [links, setLinks] = useState([])
+  const [milestones, setMilestones] = useState([])
+
+  useEffect(() => {
+    if (profile.links) {
+      const newLinks = profile.links.map((link) => {
+        return { ...link, icon: link.icon?.toLowerCase() }
+      })
+      setLinks(newLinks)
+    }
```
Comment (eddiejaoude) [inline src/Components/UserProfile/ProfilePage.js:18]: Not sure the check is needed because it is an empty array?

I think it will be cleaner to do something like this

```ts
const newLinks = profile.links.map((link) => ({ ...link, icon: link.icon?.toLowerCase()}));
```

Comment (nathgoutam93) [reply src/Components/UserProfile/ProfilePage.js:18]: Yup , it's not needed if the list data are correctly added 

I found some profiles without milestones  and gave an undefined.
so I thought why take risk just add the check for links as well 🙂

File: src/Components/Home/Users.js (hunk 2 above)
Comment (nathgoutam93) [reply src/Components/Home/Users.js:36]: Okay I'll keep it in the previous style

**Review by Vyvy-vi — APPROVED** [review]
looks good to me.
Thanks for contributing to LinkFree! :)

**Review by emmalearnscode — APPROVED** [review]

**Comment by emmalearnscode** [comment]
Looks great, thanks for contributing!

**Comment by krishguptadev** [comment]
Nice! Thanks for contributing! Waiting for this from some time :D
