### PR TITLE
Fixes Using Chips in the "add Tags" section #9103 

### LINKED ISSUE #9103: [FEATURE] Using Chips in the "add Tags" section
### Description

Currently the add Tags section looks like this:

image

It would be more convenient to add them via enter instead of having to enter a comma. At least for me I have pressed multiple times enter before using the comma.

An example on how this could work can be seen here: https://tailwind-elements.com/docs/standard/components/chips/
image

Note: it might be worth considering having both options (i.e. `enter` and `comma`).

### PR DESCRIPTION
**Pull request by Zopsss**
## Fixes Issue

Fixes #9103 

## Changes proposed
Added "enter" functionality to the "Tags" input, now we can add new tags by pressing "enter".

## Screenshots

https://github.com/EddieHubCommunity/BioDrop/assets/86093112/2ad92497-1bc6-4f72-9021-1d1120db9321

### CODE REVIEW

**Review by kumarsonsoff3 — DISMISSED** [review]
PRs not related to profile, should not include any data file. Also, you're not allowed to remove someone else json file. 

Please revert the changes from `data/alevel7.json`

**Comment by MauryanKansara** [comment]
> PRs not related to profile, should not include any data file. Also, you're not allowed to remove someone else json file.
> 
> Please revert the changes from `data/alevel7.json`

I reverted that commit and pushed the new changes. Sorry for accidently deleting someone's json file.

File: pages/account/manage/profile.js [hunk 1]
```diff
@@ -85,6 +85,8 @@ export default function Profile({ BASE_URL, profile, fileExists }) {
     };
   });
 
+  const inputRef = useRef(null);
```
[the remark this answers is not in the document]
Comment (MauryanKansara) [reply pages/account/manage/profile.js]: Made changes as you said and pushed it✌️

**Review by schmelto — APPROVED** [review]

File: components/tag/TagsInput.js [hunk 2]
```diff
@@ -1,37 +1,37 @@
-import { useRef } from "react";
 import XMarkIcon from "@heroicons/react/20/solid/XMarkIcon";
 import Input from "../form/Input";
 
-export default function TagsInput({ tags, onTagAdd, onTagRemove }) {
-  const inputRef = useRef(null);
+export default function TagsInput({ tags, onTagAdd, onTagRemove, tagInputRef }) {
```
Comment (eddiejaoude) [inline components/tag/TagsInput.js:4]: If this name was kept the same there would be less changes in the file. I think `inputRef is still descriptive in the scope of this function

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution 👍  But this now breaks the events page, please search for where the component `TagsInput` is used

Screenshot 2023-10-21 at 09 27 12

File: components/tag/TagsInput.js (hunk 2 above)
Comment (MauryanKansara) [reply components/tag/TagsInput.js:4]: so should I the `tagInputref` to `inputRef`?

**Comment by MauryanKansara** [comment]
> Thank you for your contribution 👍 But this now breaks the events page, please search for where the component `TagsInput` is used
> 
> Screenshot 2023-10-21 at 09 27 12



> Thank you for your contribution 👍 But this now breaks the events page, please search for where the component `TagsInput` is used
> 
> Screenshot 2023-10-21 at 09 27 12

can you specify steps to produce this error?

File: components/tag/TagsInput.js (hunk 2 above)
Comment (eddiejaoude) [reply components/tag/TagsInput.js:4]: Yes please 👍

**Comment by eddiejaoude** [comment]
> can you specify steps to produce this error?

I clicked on manage events, then went to edit an event.

**Comment by MauryanKansara** [comment]
> > can you specify steps to produce this error?
> 
> I clicked on manage events, then went to edit an event. You can search for where the `TagsInput` component is used, then you can test these pages also

I followed the steps and tried to edit an event, everything was working perfectly and I also searched for `TagsInput` but VS Code is showing that it is only used in `profile.js` file. Btw I have renamed the `tagInputRef` to `inputRef` so I guess this error will automatically get fixed.

**Comment by MauryanKansara** [comment]
> > can you specify steps to produce this error?
> 
> I clicked on manage events, then went to edit an event. You can search for where the `TagsInput` component is used, then you can test these pages also

in my local setup there is no option to add tags on events and VS Code is showing that `TagsInput` is only used in `profile.js` file. I also pulled changes but the `tags` options on `event manage` page is still not showing.

**Comment by badrivlog** [comment]
> in my local setup there is no option to add tags on events and VS Code is showing that `TagsInput` is only used in `profile.js` file. I also pulled changes but the `tags` options on `event manage` page is still not showing.

see screen recording below to reproduce the error

https://github.com/EddieHubCommunity/BioDrop/assets/73095526/45735c6d-f17a-4a8c-8bc2-fdb622cc5422

File: pages/account/manage/event/[[...data]].js [hunk 3]
```diff
@@ -57,6 +57,7 @@ export default function ManageEvent({ BASE_URL, event }) {
   const [endDate, setEndDate] = useState("");
   const [speakingTopic, setspeakingTopic] = useState(event.speakingTopic || "");
   const [tags, setTags] = useState(event.tags || []);
+  const inputRef = useRef(null);
```
Comment (badrivlog) [inline pages/account/manage/event/[[...data]].js:60]: I'm not sure why this variable named `inputRef`. I think naming the variable simply `inputRef` might not be very descriptive, because I see in the scope of this function has multiple input fields.

File: pages/account/manage/profile.js [hunk 4]
```diff
@@ -76,6 +76,8 @@ export default function Profile({ BASE_URL, profile, fileExists }) {
...
```
Comment (badrivlog) [inline pages/account/manage/profile.js:79]: Same here

File: pages/account/manage/event/[[...data]].js (hunk 3 above)
Comment (eddiejaoude) [reply pages/account/manage/event/[[...data]].js:60]: Yep 👍  Inside the tag component it can be `inputRef` but outside it should be `tagInputRef`

Comment (badrivlog) [reply pages/account/manage/event/[[...data]].js:60]: Yeah that makes sense

Comment (MauryanKansara) [reply pages/account/manage/event/[[...data]].js]: sorry for the late reply, I made the changes as you requested and pushed the changes.

File: pages/account/manage/event/[[...data]].js [hunk 5]
```diff
@@ -105,6 +106,10 @@ export default function ManageEvent({ BASE_URL, event }) {
   const handleSubmit = async (e) => {
     e.preventDefault();
 
+    if (document.activeElement === tagInputRef.current) {
+      console.log('testing');
```
Comment (eddiejaoude) [inline pages/account/manage/event/[[...data]].js:110]: Please remove debug code

Comment (MauryanKansara) [reply pages/account/manage/event/[[...data]].js]: Sorry I forgot to remove it before now I've removed it and pushed the changes. Thanks for addressing this.

**Review by badrivlog — APPROVED** [review]
Looks good to me👍

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you 👍

**Review by eddiejaoude — APPROVED** [review]
Sorry I was meant to approve
