### PR TITLE
fix: Changing props of button instead of replacing button

### LINKED ISSUE #7053: [BUG]: Playground page submit buttons should not be replaced
### Description

Playground page submit buttons are being replaced but should not be and should have the text updated

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by amitabh-sahu**
Closes #7053

## Fixes Issue
1. Instead of replacing the playground page submit button, changing button props (ex: text, onClick, primary)
2. Cannot read properties of undefined (reading 'filter') on UserPage.js file line no 17
3. Cannot read properties of undefined (reading 'map') on UserProfile.js file line no 50

## Changes proposed
```diff
- delete actualJson.testimonials;
+ actualJson.testimonials = actualJson.testimonials || [];
+ actualJson.socials = actualJson.socials || [];

...

-         {!formatComplete && (
-           <Button text="Format" onClick={handleFormatJson} primary={false} />
-          )}
-          {formatComplete && !validateComplete && (
-            <Button
-              text="Validate"
-              onClick={handleValidateJson}
-              primary={false}
-            />
-          )}
-          {formatComplete && validateComplete && (
-            <Button text="Preview" onClick={handlePreview} primary={true} />
-          )}
+          <Button
+            {...(!formatComplete
+              ? { text: "Format", onClick: handleFormatJson, primary: false }
+              : formatComplete && !validateComplete
+              ? {
+                  text: "Validate",
+                  onClick: handleValidateJson,
+                  primary: false,
+                }
+              : formatComplete && validateComplete
+              ? { text: "Preview", onClick: handlePreview, primary: true }
+              : { text: "", disable: true })}
+          />
```

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Point numbers 2 and 3 from the above fixes issue listing are not part of the issue, but I saw this error while working on this issue and pressed preview without adding testimonials and socials in json then it break the website.
Let me know if something has to change or if those changes have to go on a separate issue.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7141"></a>

### CODE REVIEW

File: pages/playground.js [hunk 1]
```diff
@@ -140,19 +141,7 @@ export default function Playground() {
...
-            <Button
-              text="Validate"
-              onClick={handleValidateJson}
-              primary={false}
-            />
-          )}
-          {formatComplete && validateComplete && (
-            <Button text="Preview" onClick={handlePreview} primary={true} />
-          )}
+          <Button {...(!formatComplete ? {text: "Format", onClick: handleFormatJson, primary: false} : formatComplete && !validateComplete ? {text: "Validate", onClick: handleValidateJson, primary: false} : formatComplete && validateComplete ? {text: "Preview", onClick: handlePreview, primary: true} : {text: "", disable: true})} />
```
Comment (eddiejaoude) [inline pages/playground.js:144]: Please check the formatting, this is not readable. If you have the VScode Prettier plugin installed, this should pick up our settings and do it automatically for you

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 👍  I have left an inline comment, once addressed I can review again and test

File: pages/playground.js (hunk 1 above)
Comment (amitabh-sahu) [reply pages/playground.js]: Sorry,
I have Prettier disabled for workspaces.
Pushed formatting changes.

File: pages/playground.js [hunk 2]
```diff
@@ -75,7 +75,8 @@ export default function Playground() {
       if (gitUsername && profileJson && handleValidateJson()) {
         setErrMsg("");
         let actualJson = { username: gitUsername, ...JSON.parse(profileJson) };
-        delete actualJson.testimonials;
+        actualJson.testimonials = actualJson.testimonials || [];
+        actualJson.socials = actualJson.socials || [];
```
Comment (eddiejaoude) [inline pages/playground.js:79]: Please can you explain these changes?

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 👍 

Although these changes do work, it is very difficult to read the code like this.

I suggest moving the conditions to a function, something like this...

```diff
diff --git a/pages/playground.js b/pages/playground.js
index 4ad83f7c..316fd4e2 100644
--- a/pages/playground.js
+++ b/pages/playground.js
@@ -30,6 +30,26 @@ export default function Playground() {
   const [previewModalData, setPreviewModalData] = useState();
   const [showNotification, setShowNotification] = useState(false);
 
+  const buttonProps = () => {
+    if (!formatComplete) {
+      return { text: "Format", onClick: handleFormatJson, primary: false };
+    }
+
+    if (formatComplete && !validateComplete) {
+      return {
+        text: "Validate",
+        onClick: handleValidateJson,
+        primary: false,
+      };
+    }
+
+    if (formatComplete && validateComplete) {
+      return { text: "Preview", onClick: handlePreview, primary: true };
+    }
+
+    return { text: "", disable: true };
+  };
+
   const handleValidateJson = () => {
     try {
       JSON.parse(profileJson);
@@ -141,19 +161,7 @@ export default function Playground() {
           }}
         />
         <div className="flex flex-row justify-end mb-3 gap-2">
-          <Button
-            {...(!formatComplete
-              ? { text: "Format", onClick: handleFormatJson, primary: false }
-              : formatComplete && !validateComplete
-              ? {
-                  text: "Validate",
-                  onClick: handleValidateJson,
-                  primary: false,
-                }
-              : formatComplete && validateComplete
-              ? { text: "Preview", onClick: handlePreview, primary: true }
-              : { text: "", disable: true })}
-          />
+          <Button {...buttonProps()} />
         </div>
 
         <Modal
```

File: pages/playground.js (hunk 2 above)
Comment (amitabh-sahu) [reply pages/playground.js:79]: When you press Preview with empty JSON or JSON without testimonials and socials are given an undefined error on UserPage.js on UserProfile.js file respectively

**Comment by amitabh-sahu** [comment]
> Thank you for the contribution 👍
> 
> Although these changes do work, it is very difficult to read the code like this.
> 
> I suggest moving the conditions to a function, something like this...
> 
> ```diff
> diff --git a/pages/playground.js b/pages/playground.js
> index 4ad83f7c..316fd4e2 100644
> --- a/pages/playground.js
> +++ b/pages/playground.js
> @@ -30,6 +30,26 @@ export default function Playground() {
>    const [previewModalData, setPreviewModalData] = useState();
>    const [showNotification, setShowNotification] = useState(false);
>  
> +  const buttonProps = () => {
> +    if (!formatComplete) {
> +      return { text: "Format", onClick: handleFormatJson, primary: false };
> +    }
> +
> +    if (formatComplete && !validateComplete) {
> +      return {
> +        text: "Validate",
> +        onClick: handleValidateJson,
> +        primary: false,
> +      };
> +    }
> +
> +    if (formatComplete && validateComplete) {
> +      return { text: "Preview", onClick: handlePreview, primary: true };
> +    }
> +
> +    return { text: "", disable: true };
> +  };
> +
>    const handleValidateJson = () => {
>      try {
>        JSON.parse(profileJson);
> @@ -141,19 +161,7 @@ export default function Playground() {
>            }}
>          />
>          <div className="flex flex-row justify-end mb-3 gap-2">
> -          <Button
> -            {...(!formatComplete
> -              ? { text: "Format", onClick: handleFormatJson, primary: false }
> -              : formatComplete && !validateComplete
> -              ? {
> -                  text: "Validate",
> -                  onClick: handleValidateJson,
> -                  primary: false,
> -                }
> -              : formatComplete && validateComplete
> -              ? { text: "Preview", onClick: handlePreview, primary: true }
> -              : { text: "", disable: true })}
> -          />
> +          <Button {...buttonProps()} />
>          </div>
>  
>          <Modal
> ```

Made changes and commit as you suggest

File: pages/playground.js (hunk 2 above)
Comment (eddiejaoude) [reply pages/playground.js:79]: Oh I see, yes you are correct. I think I fixed `UserProfile` for the empty socials. But we can leave these in for now as extra checks

File: pages/playground.js [hunk 3]
```diff
@@ -87,6 +88,22 @@ export default function Playground() {
     }
   };
 
+  const buttonProps = () => {
+    if (!formatComplete) {
+      return { text: "Format", onClick: handleFormatJson, primary: false };
+    } else if (formatComplete && !validateComplete) {
```
Comment (eddiejaoude) [inline pages/playground.js:94]: Because of the `return` early in the condition above these don't need to be `else if`, you can see my example here https://github.com/EddieHubCommunity/LinkFree/pull/7141#pullrequestreview-1444838449

Comment (amitabh-sahu) [reply pages/playground.js]: Thanks,
I'll keep this in mind for further
Made changes as you said

**Review by eddiejaoude — APPROVED** [review]
Looks good, thank you 👍
