### PR TITLE
Modal bug fixed in playground page

### LINKED ISSUE #7637: [BUG] Full Profile not shown
### Description

I noticed that whenever I preview a change that I want to make on my Linkfree profile, it only shows half of it. This can make users hesitant on making a PR for it.  

### Screenshots

profile preview on playground
 
 In the screenshot above, I wanted to add another link to my links section(see PR #7636 for more context), but it only shows half of my profile.  

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rajpatelbot**
## Fixes Issue
Closes #7637

## Changes proposed
Changes was proposed to fix modal design issue and make it scrollable in playground page.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (1)

## Note to reviewers
@eddiejaoude as you suggested to make full modal scrollable in PR number: #7669. Here is updated PR.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7712"></a>

### CODE REVIEW

File: components/Modal.js [hunk 1]
```diff
@@ -29,7 +29,10 @@ export default function Modal({ show = false, setShow, title, children }) {
               leaveFrom="opacity-100 translate-y-0 sm:scale-100"
               leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
             >
-              <Dialog.Panel className="relative transform overflow-hidden rounded-lg bg-white dark:bg-primary-high text-left shadow-xl transition-all m-16 sm:w-full sm:max-w-4xl max-h-screen">
+              <Dialog.Panel
+                className="relative transform overflow-hidden rounded-lg bg-white dark:bg-primary-high text-left shadow-xl transition-all m-16 sm:w-full sm:max-w-4xl max-h-screen overflow-y-auto"
+                style={{ height: "600px" }}
```
Comment (eddiejaoude) [inline components/Modal.js:34]: Please use Tailwind styles rather than custom styles, you can learn more about Tailwind height in the official docs here https://tailwindcss.com/docs/height

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Please see inline comments

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍  Thank you!
