### PR TITLE
fix: add missing comma

### LINKED ISSUE #792: [DOCS] Fix commas
### Description

*If you've already forked this repository, skip to step 3*

1. Fork the repository [here](https://github.com/EddieHubCommunity/LinkFree/fork).
2. Make a new branch named `missing_comma`.
3. Go to [`cypress/integration/search.feature`](https://github.com/EddieHubCommunity/LinkFree/blob/main/cypress/integration/search.feature) (remember to open that file in your fork!).
4. In line 21, replace the current content with the following content:

```feature
        Then I see "No users found, please try with another name." text in section "main"
```

5. Go to [`src/Components/Home/Users.js`](https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/Home/Users.js) (remember to open that file in your fork!).
6. In line 51, replace the current content with the following content:

```javascript
            <Message severity="error" text="No users found, please try with another name." />
```

Now you should be ready to make your PR and get this fixed! 🚀

### Screenshots

_No response_

### Additional information

This is a good first issue. Please leave this open to beginners and first-time contributors. 🙂

### PR DESCRIPTION
**Pull request by Abbhiishek**
Close #792 
## Changes proposed
In ``cypress/integration/search.feature``
line 21, replaced the current content with the following content:

`Then I see "No users found, please try with another name." text in section "main"`

In ` src/Components/Home/Users.js `
In line 51, replaced the current content with the following content:

`<Message severity="error" text="No users found, please try with another name." />
`

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/794"></a>

### CODE REVIEW

File: src/Components/Home/Users.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ function Users({ list }) {
           ))}
         {!!filteredList && filteredList.length === 0 && (
           <div className="p-d-flex p-jc-center p-ai-center">
-            <Message severity="error" text="No users found please try again" />
+          <Message severity="error" text="No users found, please try with another name." />
```
Comment (Panquesito7) [inline src/Components/Home/Users.js:51]:
```suggestion
            <Message severity="error" text="No users found, please try with another name." />
```

**Review by Panquesito7 — APPROVED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍
