### PR TITLE
[BUG] Added padding to Github icon

### LINKED ISSUE #7034: [BUG] Github navbar logo needs more padding and less margin. (Especially when tabbing)
### What would you like to share?

This issue is raised for the improvement of accessibility. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AliMora83**
[BUG] Github navbar logo needs more padding and less margin. (Especially when tabbing) 

closes #7034

## Fixes Issue

- Adds padding to Github icon in Navbar.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-05-21 at 15 07 06

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7097"></a>

### CODE REVIEW

**Review by ujwalkumar1995 — COMMENTED** [review]
Looks good!

**Comment by eddiejaoude** [comment]
Thank you for the contribution, could you add a screenshot before and after please.

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution, please see inline comments

**Comment by AliMora83** [comment]
Current look:
Screenshot 2023-05-23 at 09 44 13

After changes:
Screenshot 2023-05-23 at 10 11 22


Hope it works 🥳

File: components/navbar/Navbar.js [hunk 1]
```diff
@@ -252,20 +247,15 @@ export default function Navbar() {
...
-                  >
+                 <Link href="https://github.com/EddieHubCommunity/LinkFree" target="_blank" rel="noreferrer" aria-current="page">
+                <div className="ml-3 mr-2 relative p-2">
                     <FaGithub
                       className="text-primary-low hover:text-secondary-low"
                       aria-label="GitHub"
                     />
-                  </Link>
                 </div>
+                </Link>
```
Comment (eddiejaoude) [inline components/navbar/Navbar.js:257]: The indentation is not correct here

File: components/navbar/Navbar.js [hunk 2]
```diff
@@ -165,19 +165,14 @@ export default function Navbar() {
...
                   setIsOpen={setIsOpen}
                 />
-                <div className="relative">
-                  <Link
-                    href="https://github.com/EddieHubCommunity/LinkFree"
-                    aria-current="page"
-                    target="_blank"
-                    rel="noreferrer"
-                  >
+                <Link href="https://github.com/EddieHubCommunity/LinkFree" target="_blank" rel="noreferrer" aria-current="page">
```
Comment (eddiejaoude) [inline components/navbar/Navbar.js:168]: The formatting isn't quite correct here, this should be broken on to multiple lines as it was before, otherwise when someone else works on the file and saves it, Prettier will reformat the file correctly and it will make their PR seem much bigger and cause confusion

**Review by eddiejaoude — APPROVED** [review]
Thank you for the contribution 👍 

I will fix the formatting issues in a temporary branch
