### PR TITLE
enhancement - Fixed the active page highlighted feature

### LINKED ISSUE #8262: [BUG] Doc menu highlighting feature not working properly
## Description

The **documentation menu active page highlighting feature is not working**. When I open the documentation menu, the active page is not highlighted. This makes it difficult to know which page I am currently viewing.

And also we can refactor some of the code and can enhance it further.

**I would like to work on this issue if all sounds good.**

### **Before**

The highlighting function does not work properly.

image

### **After**
After improvement and refactoring multiple lines of code.

image

### Additional information

**I would like to work on this issue if all sounds good.**

### PR DESCRIPTION
**Pull request by ashrafchowdury**
## Fixes Issue

Closes #8262

## Changes proposed

* Refactored some of the code.
* Added dynamic functionality to highlight the active link.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8308"></a>

### CODE REVIEW

File: components/navbar/SideNav.js [hunk 1]
```diff
@@ -1,24 +1,27 @@
...
-            <li key={item.name}>
+            <li key={item.name} className="my-2">
               {!item.children ? (
                 <a
                   href={item.href}
                   className={classNames(
-                    item.current ? "bg-primary-low" : "hover:bg-primary-low",
-                    "group flex gap-x-3 rounded-md p-2 text-md leading-6 font-semibold text-primary-high dark:text-primary-low-medium dark:hover:text-secondary-high hover:text-secondary-high"
+                    item.href == pathname &&
+                      " bg-slate-200 dark:bg-primary-low !text-secondary-high",
```
Comment (eddiejaoude) [inline components/navbar/SideNav.js:23]: I don't think the prepended space is required as the `classNames` adds a space?

Comment (ashrafchowdury) [reply components/navbar/SideNav.js]: Resolved 👍

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍 

I think if the nav stayed open when navigating within a section that would be awesome but not a blocker for this PR
