### PR TITLE
[BUG FIX] milestones tab ui is not consistent with others

### LINKED ISSUE #7945: [BUG] milestones tab ui is not consistent with others
### Description

in milestones tab: there is no padding between add milestone button and alert.

### Screenshots

currently:
Screenshot 2023-07-03 at 4 47 20 PM

it should be like event tab:
Screenshot 2023-07-03 at 4 47 29 PM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ZeeMonk-pixel**
## Fixes Issue
Closes #7945

BEFORE FIX
250541828-960d59cb-5a73-45e9-865f-baf3451ea3e2
AFTER FIX
Screenshot 2023-07-04 034810

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7960"></a>

### CODE REVIEW

File: pages/account/manage/milestones.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ export default function ManageMilestones({ milestones }) {
       <Page>
         <Navigation />
 
-        <Button href="/account/manage/milestone">
```
Comment (eddiejaoude) [inline pages/account/manage/milestones.js:53]: I don't think this change is needed

File: components/user/UserMilestones.js [hunk 2]
```diff
@@ -10,7 +10,8 @@ export default function UserMilestones({ milestones, manage = false }) {
   return (
     <>
       {!milestones?.length && (
-        <Alert type="info" message="No milestones found" />
+        <div className="m-6 mt-10"><Alert type="info" message="No milestones found" /></div>
```
Comment (eddiejaoude) [inline components/user/UserMilestones.js:13]: The other areas do not have it wrapped https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserTestimonials.js#L11

We should try to be consistent in the visual result and also the way it is implemented

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 👍 I have left inline comments

File: pages/account/manage/milestones.js (hunk 1 above)
Comment (ZeeMonk-pixel) [reply pages/account/manage/milestones.js:53]: Yeah, it was not intentional, I mistakenly left a white space there after the quotation. how do I fix it?

File: components/user/UserMilestones.js (hunk 2 above)
Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: it was wrapped in the events tab. Check the highlights
Screenshot 2023-07-05 114137
this is for the changes i made on milestone
milestone

NOTE: The alert isnt popping up for the testimonials tab. the picture below shows what I'm getting with no testimonial but the alert message should be "No testimonials found". it doesn't look like the alert is popping up
Screenshot 2023-07-05 115426

File: pages/account/manage/milestones.js (hunk 1 above)
Comment (ZeeMonk-pixel) [reply pages/account/manage/milestones.js:53]: I've edited this and should reflect when i push after the others has been resolved.

Comment (eddiejaoude) [reply pages/account/manage/milestones.js:53]: ok thanks 👍

File: components/user/UserMilestones.js (hunk 2 above)
Comment (eddiejaoude) [reply components/user/UserMilestones.js:13]: Oh good spot, we should not show the `reorder` button if there are no results and should show the alert. As your PR is small, do you want to fix it as part of this?

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: Yes I will love to. I'm guessing we are okay with the milestone?

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: So I noticed, the UserTestimonial component (https://github.com/EddieHubCommunity/LinkFree/blob/main/components/user/UserTestimonials.js#L11) is not on the testimonials page (https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/account/manage/testimonials.js). Is it supposed to be that way?

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: If it is that way, then the fix for this will be to show the Alert component only if there's no testimonial

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: > If it is that way, then the fix for this will be to show the Alert component only if there's no testimonial

I have it working this way already.

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: Hi, good morning. I'm still waiting on a response on this

Comment (ZeeMonk-pixel) [reply components/user/UserMilestones.js:13]: Reusing the component is just one line of code and I won't need to use the alert component. This is how it looks with the UserTestimonials component.
testChange

this is the result (same result)
change

File: pages/account/manage/testimonials.js [hunk 3]
```diff
@@ -99,75 +100,78 @@ export default function ManageTestimonials({ BASE_URL, testimonials }) {
           additionalMessage="Your profile information has been saved successfully."
         />
 
-        <div>
-          <h3 className="text-lg font-medium leading-6 text-primary-high mb-4">
-            Testimonials you have received, toggle to show on your Profile
-          </h3>
-        </div>
+        {!testimonials?.length ? <Alert type="info" message="No testimonials found" /> :
+          <>
```
Comment (eddiejaoude) [inline pages/account/manage/testimonials.js:104]: I think the `:` makes it difficult to read, other places in the code we use the condition twice

- `!testimonials ...`
- `testimonials ...`

Comment (ZeeMonk-pixel) [reply pages/account/manage/testimonials.js:104]: Okay. I will get on it now.

Comment (ZeeMonk-pixel) [reply pages/account/manage/testimonials.js:105]: fixed 

testimonial fix
fix

Comment (ZeeMonk-pixel) [reply pages/account/manage/testimonials.js:105]: I made a new update
test update

result
change

**Comment by eddiejaoude** [comment]
Thank you for the collaboration 👍 I will merge to a temporary branch and make some tweaks

**Comment by ZeeMonk-pixel** [comment]
Thanks Eddie
